### ISSUE TITLE
Unnecessary files

### ISSUE THREAD

**Issue by SamuelVilz** [FAU-DLM/wsi_processing_pipeline#2]
"__init__.py", "example_pipeline.ipynb" and "untitled.txt" are empty and should thus be deleted

**Comment by ChristophNeuner** [comment]
__init__.py is neccessary for python to recognize this lib as a python package.
https://docs.python.org/3/tutorial/modules.html#packages

**Comment by ChristophNeuner** [comment]
https://github.com/FAU-DLM/wsi_processing_pipeline/commit/5875c6b49ef4832738212813ee71fd962669c093
